name: rest_api_annotation
description: A starting point for Dart libraries or applications.
version: 1.0.0

environment:
  sdk: ^3.2.2

dependencies:
  dio: ^5.4.0

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
